[book]
title = "Licence Radio Amateur"
authors = ["F6GPX - Jean-Luc Fortin"]
description = "Cours de préparation au certificat d'opérateur du service amateur"
language = "fr"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/scttpr/licence-radio"
edit-url-template = "https://github.com/scttpr/licence-radio/edit/main/{path}"
site-url = "/licence-radio/"
no-section-label = false

[output.html.fold]
enable = true
level = 0

[output.html.print]
enable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
